/**
 * Top-level path segments that must never be treated as legacy city slugs in middleware.
 * When adding a new top-level route under src/app, add its segment here.
 * Unknown segments are no longer redirected to /search — they fall through to Next.js routing.
 */
export const PUBLIC_STATIC_SEGMENTS = new Set([
  "about",
  "account",
  "admin",
  "agents",
  "ambassador",
  "become-a-field-verifier",
  "become-a-legal-partner",
  "become-an-ambassador",
  "blog",
  "browse",
  "buy",
  "careers",
  "contact",
  "cookie-policy",
  "cookies",
  "disclaimer",
  "explore",
  "home",
  "hotel",
  "land",
  "legal",
  "legal-partner",
  "legal-verification",
  "list",
  "list-property",
  "listing",
  "locations",
  "moderation",
  "odogwu_stankings",
  "payments",
  "plans",
  "post-property",
  "pricing",
  "privacy",
  "profile",
  "properties",
  "property",
  "property-verification",
  "rent",
  "request-home",
  "request-property",
  "safety",
  "saved",
  "search",
  "services",
  "shortlet",
  "support",
  "swipe",
  "swipe-homes",
  "terms",
  "verifier",
  "verify-agent",
  "verify-property",
  "why-verified",
  "houses",
  "intent",
  "offline",
  "l",
  "auth",
  "agent",
  "lex",
  "staff",
  "dev",
  "email",
  "api",
  "well-known",
]);

/** First path segment that must never be treated as a legacy city slug. */
export const RESERVED_PATH_PREFIXES = new Set([
  ...PUBLIC_STATIC_SEGMENTS,
]);
