/** Top-level app routes — keep in sync with `src/app/(public)` and sibling route groups. */
export const PUBLIC_STATIC_SEGMENTS = new Set([
  "about",
  "account",
  "admin",
  "agents",
  "blog",
  "browse",
  "buy",
  "careers",
  "contact",
  "cookie-policy",
  "cookies",
  "disclaimer",
  "explore",
  "home",
  "hotel",
  "land",
  "legal",
  "list",
  "list-property",
  "listing",
  "moderation",
  "odogwu_stankings",
  "post-property",
  "privacy",
  "profile",
  "properties",
  "property",
  "rent",
  "request-home",
  "request-property",
  "safety",
  "saved",
  "search",
  "shortlet",
  "support",
  "swipe",
  "swipe-homes",
  "terms",
  "verify-agent",
  "why-verified",
  "houses",
  "offline",
  "l",
  "auth",
  "agent",
  "lex",
  "dev",
  "api",
  "well-known",
]);

/** First path segment that must never be treated as a legacy city slug. */
export const RESERVED_PATH_PREFIXES = new Set([
  ...PUBLIC_STATIC_SEGMENTS,
]);
