import { buildPhotoSchema, tag } from "./helpers";

/** Vehicle marketplace photo taxonomy. */
export const VEHICLE_PHOTO_SCHEMA = buildPhotoSchema({
  id: "vehicle",
  tags: [
    tag("cover", "Cover Photo"),
    tag("exterior_front", "Exterior Front"),
    tag("exterior_rear", "Exterior Rear"),
    tag("left_side", "Left Side"),
    tag("right_side", "Right Side"),
    tag("interior_front", "Interior Front"),
    tag("interior_rear", "Interior Rear"),
    tag("dashboard", "Dashboard"),
    tag("steering_wheel", "Steering Wheel"),
    tag("odometer", "Odometer"),
    tag("engine", "Engine"),
    tag("boot", "Boot / Trunk"),
    tag("tyres", "Tyres"),
    tag("rims", "Rims"),
    tag("vin_plate", "VIN Plate"),
    tag("keys", "Keys"),
    tag("service_book", "Service Book"),
    tag("spare_tyre", "Spare Tyre"),
    tag("accessories", "Accessories"),
    tag("damage", "Damage"),
    tag("other", "Other"),
  ],
  uploadSequence: [
    "cover",
    "exterior_front",
    "exterior_rear",
    "left_side",
    "right_side",
    "interior_front",
    "dashboard",
    "engine",
    "tyres",
    "other",
  ],
  preferredCoverIds: ["cover", "exterior_front", "exterior_rear", "left_side"],
  poorCoverIds: ["other", "damage", "odometer", "keys", "service_book", "vin_plate"],
  recommendedShots: ["Front", "Rear", "Interior", "Dashboard", "Engine", "Tyres"],
  uploadHint: "Start with front, rear, interior, dashboard, and engine",
  labelPlaceholder: "Photo label…",
});
