import type { ListingCategoryConfig } from "../types";

export const PROPERTIES_LISTING_CONFIG: ListingCategoryConfig = {
  id: "properties",
  label: "Property",
  description: "Pick the type of item you want to sell on Yike.",
  assetCategory: "props",
  defaultAsset: "house",
  steps: [
    {
      id: "type_selection",
      title: "What are you listing?",
      subtitle: "Pick the type of item you want to sell on Yike.",
      fields: [
        {
          id: "property_type",
          label: "Property Type",
          type: "card_select",
          stepId: "type_selection",
          validation: [{ type: "required", message: "Please select a property category." }],
          options: [
            { id: "house", label: "House", subtitle: "Detached, Semi-detached, Terraced, Bungalow", assetCategory: "props", assetName: "house" },
            { id: "apartment", label: "Apartment", subtitle: "Flats, Studios, Penthouses", assetCategory: "props", assetName: "apartment", badge: "Popular" },
            { id: "land", label: "Land", subtitle: "Residential, Commercial, Agricultural", assetCategory: "props", assetName: "land" },
            { id: "duplex", label: "Duplex", subtitle: "Semi or Fully Detached", assetCategory: "props", assetName: "duplex" },
            { id: "commercial", label: "Commercial", subtitle: "Offices, Shops, Plaza, Complexes", assetCategory: "props", assetName: "commercial" },
            { id: "shortlet", label: "Shortlet / Rental", subtitle: "Short-term & Vacation rentals", assetCategory: "props", assetName: "hotel" },
            { id: "warehouse", label: "Warehouse", subtitle: "Industrial & Storage Facilities", assetCategory: "props", assetName: "warehouse" },
            { id: "hotel", label: "Hotel", subtitle: "Hotels, Lodge, Guest House", assetCategory: "props", assetName: "hotel" },
            { id: "other-property", label: "Other", subtitle: "Specify other property type", assetCategory: "props", assetName: "other-property" },
          ],
        },
      ],
    },
    {
      id: "property_details",
      title: "Tell us about your property",
      subtitle: "Fill in the details. We'll auto-detect some info.",
      fields: [
        {
          id: "title",
          label: "Property Title",
          type: "text",
          placeholder: "e.g. 4 Bedroom Detached Duplex with BQ",
          stepId: "property_details",
          validation: [{ type: "required", message: "Title is required." }],
        },
        {
          id: "listing_purpose",
          label: "Listing Purpose",
          type: "dropdown",
          stepId: "property_details",
          defaultValue: "For Sale",
          options: [
            { id: "For Sale", label: "For Sale" },
            { id: "For Rent", label: "For Rent" },
            { id: "Shortlet", label: "Shortlet / Daily" },
            { id: "Lease", label: "Commercial Lease" },
          ],
          validation: [{ type: "required", message: "Listing purpose is required." }],
        },
        {
          id: "sub_type",
          label: "Sub Type",
          type: "dropdown",
          stepId: "property_details",
          options: [
            { id: "Detached Duplex", label: "Detached Duplex" },
            { id: "Semi-Detached Duplex", label: "Semi-Detached Duplex" },
            { id: "Terraced Duplex", label: "Terraced Duplex" },
            { id: "Block of Flats", label: "Block of Flats" },
            { id: "Bungalow", label: "Bungalow" },
            { id: "Serviced Apartment", label: "Serviced Apartment" },
            { id: "Residential Land", label: "Residential Land" },
            { id: "Commercial Land", label: "Commercial Land" },
          ],
        },
        {
          id: "bedrooms",
          label: "Bedrooms",
          type: "dropdown",
          stepId: "property_details",
          dependencies: [
            { field: "property_type", operator: "not_equals", value: "land" },
            { field: "property_type", operator: "not_equals", value: "warehouse" },
          ],
          options: [
            { id: "1 Bedroom", label: "1 Bedroom" },
            { id: "2 Bedrooms", label: "2 Bedrooms" },
            { id: "3 Bedrooms", label: "3 Bedrooms" },
            { id: "4 Bedrooms", label: "4 Bedrooms" },
            { id: "5 Bedrooms", label: "5 Bedrooms" },
            { id: "6+ Bedrooms", label: "6+ Bedrooms" },
          ],
          validation: [{ type: "required", message: "Bedrooms is required." }],
        },
        {
          id: "bathrooms",
          label: "Bathrooms",
          type: "dropdown",
          stepId: "property_details",
          dependencies: [{ field: "property_type", operator: "not_equals", value: "land" }],
          options: [
            { id: "1 Bathroom", label: "1 Bathroom" },
            { id: "2 Bathrooms", label: "2 Bathrooms" },
            { id: "3 Bathrooms", label: "3 Bathrooms" },
            { id: "4 Bathrooms", label: "4 Bathrooms" },
            { id: "5 Bathrooms", label: "5 Bathrooms" },
            { id: "6+ Bathrooms", label: "6+ Bathrooms" },
          ],
          validation: [{ type: "required", message: "Bathrooms is required." }],
        },
        {
          id: "furnishing",
          label: "Furnishing",
          type: "dropdown",
          stepId: "property_details",
          dependencies: [{ field: "property_type", operator: "not_equals", value: "land" }],
          options: [
            { id: "Furnished", label: "Furnished" },
            { id: "Semi-Furnished", label: "Semi-Furnished" },
            { id: "Unfurnished", label: "Unfurnished" },
          ],
        },
        {
          id: "condition",
          label: "Property Condition",
          type: "dropdown",
          stepId: "property_details",
          options: [
            { id: "Newly Built", label: "Newly Built" },
            { id: "Fairly Used", label: "Fairly Used" },
            { id: "Under Construction", label: "Under Construction" },
            { id: "Renovation Needed", label: "Renovation Needed" },
          ],
        },
        {
          id: "state",
          label: "State",
          type: "dropdown",
          stepId: "property_details",
          options: [
            { id: "Lagos", label: "Lagos" },
            { id: "Abuja FCT", label: "Abuja FCT" },
            { id: "Rivers", label: "Rivers" },
            { id: "Oyo", label: "Oyo" },
            { id: "Kano", label: "Kano" },
            { id: "Delta", label: "Delta" },
            { id: "Edo", label: "Edo" },
            { id: "Anambra", label: "Anambra" },
            { id: "Enugu", label: "Enugu" },
            { id: "Ogun", label: "Ogun" },
          ],
          validation: [{ type: "required", message: "State is required." }],
        },
        {
          id: "lga",
          label: "LGA",
          type: "dropdown",
          stepId: "property_details",
          options: [
            { id: "Lekki", label: "Lekki" },
            { id: "Ikeja", label: "Ikeja" },
            { id: "Eti-Osa", label: "Eti-Osa" },
            { id: "Ikoyi", label: "Ikoyi" },
            { id: "Victoria Island", label: "Victoria Island" },
            { id: "Alimosho", label: "Alimosho" },
            { id: "Surulere", label: "Surulere" },
          ],
        },
        {
          id: "area",
          label: "Area / Estate",
          type: "text",
          placeholder: "e.g. Chevron, Lekki Phase 1, Ikoyi GRA",
          stepId: "property_details",
        },
        {
          id: "price",
          label: "Price (₦)",
          type: "currency",
          placeholder: "120,000,000",
          stepId: "property_details",
          validation: [{ type: "required", message: "Price is required." }],
        },
        {
          id: "negotiable",
          label: "Negotiable?",
          type: "radio",
          stepId: "property_details",
          defaultValue: "Yes",
          options: [
            { id: "Yes", label: "Yes" },
            { id: "No", label: "No" },
          ],
        },
        {
          id: "land_size",
          label: "Land Size",
          type: "text",
          placeholder: "e.g. 600 sqm",
          stepId: "property_details",
        },
        {
          id: "building_size",
          label: "Building Size",
          type: "text",
          placeholder: "e.g. 420 sqm",
          stepId: "property_details",
          dependencies: [{ field: "property_type", operator: "not_equals", value: "land" }],
        },
        {
          id: "title_document",
          label: "Title Document",
          type: "dropdown",
          stepId: "property_details",
          options: [
            { id: "C of O", label: "Certificate of Occupancy (C of O)" },
            { id: "Governor's Consent", label: "Governor's Consent" },
            { id: "Gazette", label: "Gazette" },
            { id: "Deed of Assignment", label: "Deed of Assignment" },
            { id: "Registered Survey", label: "Registered Survey" },
            { id: "Excision", label: "Excision" },
          ],
        },
      ],
    },
    {
      id: "media_photos",
      title: "Add photos & review",
      subtitle: "Upload photos and review your listing before publishing.",
      fields: [
        {
          id: "photos",
          label: "Photos *",
          type: "photo_upload",
          stepId: "media_photos",
          helpText: "💡 Tip: First photo will be your cover photo.",
          validation: [{ type: "minPhotos", value: 1, message: "Please upload at least 1 photo." }],
        },
        {
          id: "description",
          label: "Property Description",
          type: "text",
          placeholder: "Describe estate security, power supply, water treatment, proximity to schools...",
          stepId: "media_photos",
        },
      ],
    },
  ],
};
