import type { ListingCategoryConfig } from "../types";

export const VEHICLES_LISTING_CONFIG: ListingCategoryConfig = {
  id: "vehicles",
  label: "Vehicles & Transport",
  description: "Sell or list cars, SUVs, trucks, buses, commercial fleet, or machinery.",
  assetCategory: "cars",
  defaultAsset: "car",
  steps: [
    {
      id: "type_selection",
      title: "Select Vehicle Type",
      subtitle: "Choose the body category for your vehicle to customize specs.",
      fields: [
        {
          id: "vehicle_type",
          label: "Vehicle Category",
          type: "card_select",
          stepId: "type_selection",
          validation: [{ type: "required", message: "Please select a vehicle category." }],
          options: [
            { id: "car", label: "Saloon & Sedan", subtitle: "Standard 4-door cars", assetCategory: "cars", assetName: "car" },
            { id: "suv", label: "SUV & Crossover", subtitle: "Compact & full-size SUVs", assetCategory: "cars", assetName: "suv", badge: "Popular" },
            { id: "truck", label: "Pickup & Truck", subtitle: "Commercial & light trucks", assetCategory: "cars", assetName: "truck" },
            { id: "dumper", label: "Tipper & Dumper", subtitle: "Heavy construction tippers", assetCategory: "cars", assetName: "dumper" },
            { id: "hiace-bus", label: "Delivery & Van", subtitle: "Passenger & cargo vans", assetCategory: "cars", assetName: "hiace-bus" },
            { id: "coaster-bus", label: "Coaster & Bus", subtitle: "Intercity & commercial buses", assetCategory: "cars", assetName: "coaster-bus" },
            { id: "motorcycle", label: "Motorcycle", subtitle: "2-wheel & 3-wheel bikes", assetCategory: "cars", assetName: "motorcycle" },
            { id: "keke-napep", label: "Tricycle / Keke", subtitle: "Commercial passenger keke", assetCategory: "cars", assetName: "keke-napep" },
            { id: "equipment", label: "Heavy Machinery", subtitle: "Excavators & earthmovers", assetCategory: "cars", assetName: "equipment" },
            { id: "Trailer-Truck", label: "Trailer & Haulage", subtitle: "Heavy haulage & flatbeds", assetCategory: "cars", assetName: "Trailer-Truck" },
          ],
        },
      ],
    },
    {
      id: "vehicle_details",
      title: "Vehicle Specifications & Details",
      subtitle: "Provide key details so buyers can verify make, condition, and pricing.",
      fields: [
        {
          id: "listing_type",
          label: "Listing Purpose",
          type: "radio",
          stepId: "vehicle_details",
          defaultValue: "sale",
          options: [
            { id: "sale", label: "For Sale" },
            { id: "rent", label: "For Rent / Hire" },
          ],
          validation: [{ type: "required", message: "Please select listing purpose." }],
        },
        {
          id: "rental_period",
          label: "Rental Rate Period",
          type: "dropdown",
          stepId: "vehicle_details",
          dependencies: [{ field: "listing_type", operator: "equals", value: "rent" }],
          options: [
            { id: "day", label: "Per Day" },
            { id: "week", label: "Per Week" },
            { id: "month", label: "Per Month" },
          ],
        },
        {
          id: "make",
          label: "Vehicle Make / Brand",
          type: "text",
          placeholder: "e.g. Toyota, Mercedes-Benz, Lexus, Caterpillar",
          stepId: "vehicle_details",
          validation: [{ type: "required", message: "Make is required." }],
        },
        {
          id: "model",
          label: "Model",
          type: "text",
          placeholder: "e.g. Camry, GLE 450, RX 350, D8T",
          stepId: "vehicle_details",
          validation: [{ type: "required", message: "Model is required." }],
        },
        {
          id: "year",
          label: "Year of Manufacture",
          type: "number",
          placeholder: "e.g. 2022",
          stepId: "vehicle_details",
          validation: [
            { type: "required", message: "Year is required." },
            { type: "min", value: 1970, message: "Year must be 1970 or later." },
            { type: "max", value: 2027, message: "Invalid year." },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "foreign_used", label: "Foreign Used (Tokunbo)" },
            { id: "nigerian_used", label: "Nigerian Used" },
            { id: "brand_new", label: "Brand New" },
          ],
          validation: [{ type: "required", message: "Condition is required." }],
        },
        {
          id: "mileage",
          label: "Mileage (km)",
          type: "number",
          placeholder: "e.g. 45000",
          stepId: "vehicle_details",
          dependencies: [{ field: "condition", operator: "not_equals", value: "brand_new" }],
        },
        {
          id: "transmission",
          label: "Transmission",
          type: "radio",
          stepId: "vehicle_details",
          dependencies: [
            { field: "vehicle_type", operator: "not_equals", value: "motorcycle" },
            { field: "vehicle_type", operator: "not_equals", value: "keke-napep" },
          ],
          options: [
            { id: "automatic", label: "Automatic" },
            { id: "manual", label: "Manual" },
          ],
        },
        {
          id: "price",
          label: "Asking Price (₦)",
          type: "currency",
          placeholder: "e.g. 15,000,000",
          stepId: "vehicle_details",
          validation: [
            { type: "required", message: "Price is required." },
            { type: "min", value: 100000, message: "Price must be at least ₦100,000." },
          ],
        },
        {
          id: "state",
          label: "State",
          type: "text",
          placeholder: "e.g. Lagos, Abuja FCT, Rivers",
          stepId: "vehicle_details",
          validation: [{ type: "required", message: "State is required." }],
        },
        {
          id: "city",
          label: "City / Location",
          type: "text",
          placeholder: "e.g. Ikeja, Lekki Phase 1, Victoria Island",
          stepId: "vehicle_details",
          validation: [{ type: "required", message: "City is required." }],
        },
      ],
    },
    {
      id: "media_photos",
      title: "Upload Photos & Complete",
      subtitle: "Add clear photos of the exterior, interior, and dashboard to attract buyers.",
      fields: [
        {
          id: "photos",
          label: "Vehicle Photos",
          type: "photo_upload",
          stepId: "media_photos",
          helpText: "Upload at least 2 clear photos. Drag to reorder.",
          validation: [{ type: "minPhotos", value: 2, message: "Please upload at least 2 photos." }],
        },
        {
          id: "description",
          label: "Detailed Description",
          type: "text",
          placeholder: "Mention any custom upgrades, service history, registration status...",
          stepId: "media_photos",
        },
      ],
    },
  ],
};
