import type { ListingCategoryConfig } from "../types";

export const VEHICLES_LISTING_CONFIG: ListingCategoryConfig = {
  id: "vehicles",
  label: "Vehicle",
  description: "Pick the type of item you want to sell on Yike.",
  assetCategory: "cars",
  defaultAsset: "car",
  steps: [
    {
      id: "type_selection",
      title: "What are you listing?",
      subtitle: "Pick the type of item you want to sell on Yike.",
      fields: [
        {
          id: "vehicle_type",
          label: "Vehicle Type",
          type: "card_select",
          stepId: "type_selection",
          validation: [{ type: "required", message: "Please select a vehicle type." }],
          options: [
            { id: "car", label: "Car", subtitle: "Sedans, Hatchbacks & more", assetCategory: "cars", assetName: "car" },
            { id: "suv", label: "SUV", subtitle: "Sport Utility Vehicles", assetCategory: "cars", assetName: "suv", badge: "Popular" },
            { id: "truck", label: "Truck", subtitle: "Pickup, Trucks & Trailers", assetCategory: "cars", assetName: "truck" },
            { id: "bus", label: "Bus", subtitle: "Mini buses, Coaster & Buses", assetCategory: "cars", assetName: "coaster-bus" },
            { id: "motorcycle", label: "Motorcycle", subtitle: "Bikes & Scooters", assetCategory: "cars", assetName: "motorcycle" },
            { id: "equipment", label: "Equipment", subtitle: "Heavy equipment & machines", assetCategory: "cars", assetName: "equipment" },
            { id: "dumper", label: "Dumper", subtitle: "Tipper & dumper trucks", assetCategory: "cars", assetName: "dumper" },
            { id: "hiace-bus", label: "Hiace Bus", subtitle: "Passenger & cargo vans", assetCategory: "cars", assetName: "hiace-bus" },
            { id: "luxurious-bus", label: "Luxurious Bus", subtitle: "Intercity executive buses", assetCategory: "cars", assetName: "luxurious-bus" },
            { id: "mini-van", label: "Mini Van", subtitle: "Family & commercial vans", assetCategory: "cars", assetName: "mini-van" },
            { id: "keke-napep", label: "Keke Napep", subtitle: "Tricycle passenger commercial", assetCategory: "cars", assetName: "keke-napep" },
            { id: "Tipper-Trailer", label: "Tipper Trailer", subtitle: "Heavy haulage tippers", assetCategory: "cars", assetName: "Tipper-Trailer" },
            { id: "Trailer-Truck", label: "Trailer Truck", subtitle: "Full articulated trailers", assetCategory: "cars", assetName: "Trailer-Truck" },
            { id: "trailer-truck-head", label: "Trailer Truck Head", subtitle: "Tractor heads", assetCategory: "cars", assetName: "trailer-truck-head" },
            { id: "Trailer-Haulage-Bucket", label: "Trailer Haulage Bucket", subtitle: "Bulk cargo buckets", assetCategory: "cars", assetName: "Trailer-Haulage-Bucket" },
            { id: "Flatbed-Trailers-Truck", label: "Flatbed Trailer", subtitle: "Container & flatbed haulage", assetCategory: "cars", assetName: "Flatbed-Trailers-Truck" },
            { id: "Low-Loader-Truck", label: "Low Loader", subtitle: "Equipment transport lowbeds", assetCategory: "cars", assetName: "Low-Loader-Truck" },
          ],
        },
      ],
    },
    {
      id: "vehicle_details",
      title: "Tell us about your vehicle",
      subtitle: "Fill in the details. We'll auto-detect some info.",
      fields: [
        {
          id: "make",
          label: "Make",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "Toyota", label: "Toyota" },
            { id: "Mercedes-Benz", label: "Mercedes-Benz" },
            { id: "Lexus", label: "Lexus" },
            { id: "Honda", label: "Honda" },
            { id: "Hyundai", label: "Hyundai" },
            { id: "Kia", label: "Kia" },
            { id: "Ford", label: "Ford" },
            { id: "Nissan", label: "Nissan" },
            { id: "BMW", label: "BMW" },
            { id: "Land Rover", label: "Land Rover" },
            { id: "Caterpillar", label: "Caterpillar" },
            { id: "SinoTruck", label: "SinoTruck (HOWO)" },
          ],
          validation: [{ type: "required", message: "Make is required." }],
        },
        {
          id: "model",
          label: "Model",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "Corolla", label: "Corolla" },
            { id: "Camry", label: "Camry" },
            { id: "Highlander", label: "Highlander" },
            { id: "RAV4", label: "RAV4" },
            { id: "Prado", label: "Prado" },
            { id: "Hilux", label: "Hilux" },
            { id: "RX 350", label: "RX 350" },
            { id: "ES 350", label: "ES 350" },
            { id: "GLE 450", label: "GLE 450" },
            { id: "C300", label: "C300" },
            { id: "Accord", label: "Accord" },
            { id: "Civic", label: "Civic" },
          ],
          validation: [{ type: "required", message: "Model is required." }],
        },
        {
          id: "year",
          label: "Year",
          type: "dropdown",
          stepId: "vehicle_details",
          options: Array.from({ length: 27 }, (_, i) => {
            const yr = String(2026 - i);
            return { id: yr, label: yr };
          }),
          validation: [{ type: "required", message: "Year is required." }],
        },
        {
          id: "condition",
          label: "Condition",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "Foreign Used", label: "Foreign Used" },
            { id: "Nigerian Used", label: "Nigerian Used" },
            { id: "Brand New", label: "Brand New" },
          ],
          validation: [{ type: "required", message: "Condition is required." }],
        },
        {
          id: "body_type",
          label: "Body Type",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "Sedan", label: "Sedan" },
            { id: "SUV", label: "SUV" },
            { id: "Hatchback", label: "Hatchback" },
            { id: "Pickup", label: "Pickup" },
            { id: "Coupe", label: "Coupe" },
            { id: "Convertible", label: "Convertible" },
            { id: "Bus", label: "Bus" },
            { id: "Van", label: "Van" },
          ],
        },
        {
          id: "color",
          label: "Color",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "Red", label: "🔴 Red" },
            { id: "Black", label: "⚫ Black" },
            { id: "White", label: "⚪ White" },
            { id: "Silver", label: "⚪ Silver" },
            { id: "Blue", label: "🔵 Blue" },
            { id: "Grey", label: "🔘 Grey" },
            { id: "Gold", label: "🟡 Gold" },
            { id: "Brown", label: "🟤 Brown" },
          ],
        },
        {
          id: "price",
          label: "Price (₦)",
          type: "currency",
          placeholder: "9,500,000",
          stepId: "vehicle_details",
          validation: [{ type: "required", message: "Price is required." }],
        },
        {
          id: "negotiable",
          label: "Negotiable?",
          type: "radio",
          stepId: "vehicle_details",
          defaultValue: "Yes",
          options: [
            { id: "Yes", label: "Yes" },
            { id: "No", label: "No" },
          ],
        },
        {
          id: "mileage",
          label: "Mileage (km)",
          type: "number",
          placeholder: "95,000",
          stepId: "vehicle_details",
          dependencies: [{ field: "condition", operator: "not_equals", value: "Brand New" }],
          validation: [{ type: "required", message: "Mileage is required." }],
        },
        {
          id: "transmission",
          label: "Transmission",
          type: "dropdown",
          stepId: "vehicle_details",
          dependencies: [{ field: "vehicle_type", operator: "not_equals", value: "motorcycle" }],
          options: [
            { id: "Automatic", label: "Automatic" },
            { id: "Manual", label: "Manual" },
            { id: "CVT", label: "CVT" },
          ],
          validation: [{ type: "required", message: "Transmission is required." }],
        },
        {
          id: "fuel_type",
          label: "Fuel Type",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "Petrol", label: "Petrol" },
            { id: "Diesel", label: "Diesel" },
            { id: "Hybrid", label: "Hybrid" },
            { id: "Electric", label: "Electric" },
            { id: "CNG", label: "CNG" },
          ],
          validation: [{ type: "required", message: "Fuel type is required." }],
        },
        {
          id: "drive_type",
          label: "Drive Type",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "FWD", label: "FWD (Front-Wheel Drive)" },
            { id: "RWD", label: "RWD (Rear-Wheel Drive)" },
            { id: "AWD", label: "AWD (All-Wheel Drive)" },
            { id: "4WD", label: "4WD (4x4 Four-Wheel Drive)" },
          ],
        },
        {
          id: "engine_capacity",
          label: "Engine Capacity",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "1.8L", label: "1.8L" },
            { id: "2.0L", label: "2.0L" },
            { id: "2.4L", label: "2.4L" },
            { id: "2.5L", label: "2.5L" },
            { id: "3.0L", label: "3.0L" },
            { id: "3.5L V6", label: "3.5L V6" },
            { id: "4.0L V8", label: "4.0L V8" },
            { id: "5.7L V8", label: "5.7L V8" },
          ],
        },
        {
          id: "doors",
          label: "Number of Doors",
          type: "dropdown",
          stepId: "vehicle_details",
          dependencies: [{ field: "vehicle_type", operator: "not_equals", value: "motorcycle" }],
          options: [
            { id: "2 Doors", label: "2 Doors" },
            { id: "4 Doors", label: "4 Doors" },
            { id: "5 Doors", label: "5 Doors" },
          ],
        },
        {
          id: "state",
          label: "State",
          type: "dropdown",
          stepId: "vehicle_details",
          options: [
            { id: "Lagos", label: "Lagos" },
            { id: "Abuja FCT", label: "Abuja FCT" },
            { id: "Rivers", label: "Rivers" },
            { id: "Oyo", label: "Oyo" },
            { id: "Kano", label: "Kano" },
            { id: "Delta", label: "Delta" },
            { id: "Edo", label: "Edo" },
            { id: "Anambra", label: "Anambra" },
            { id: "Enugu", label: "Enugu" },
            { id: "Ogun", label: "Ogun" },
          ],
        },
        {
          id: "city",
          label: "City / Location",
          type: "text",
          placeholder: "e.g. Lekki Phase 1, Ikeja, Victoria Island",
          stepId: "vehicle_details",
        },
      ],
    },
    {
      id: "media_photos",
      title: "Add photos & review",
      subtitle: "Upload photos and review your listing before publishing.",
      fields: [
        {
          id: "photos",
          label: "Photos *",
          type: "photo_upload",
          stepId: "media_photos",
          helpText: "💡 Tip: First photo will be your cover photo.",
          validation: [{ type: "minPhotos", value: 1, message: "Please upload at least 1 photo." }],
        },
        {
          id: "description",
          label: "Detailed Description",
          type: "text",
          placeholder: "Mention custom upgrades, service history, inspection notes...",
          stepId: "media_photos",
        },
      ],
    },
  ],
};
