/**
 * Property category manifest — metadata only. Land / commercial visibility
 * is resolved via named rule ids (rules/registry.ts), never inline
 * conditionals in this file or in the engines.
 */
import type { CategoryManifest } from "../types";

export const PROPERTY_CATEGORY_MANIFEST: CategoryManifest = {
  id: "property",
  version: 1,
  label: "Property",
  assetType: "PROPERTY",
  submitAdapter: "property",
  steps: [
    { id: "listing_type", title: "Listing type", fieldIds: ["listing_type"] },
    { id: "property_type", title: "Property type", fieldIds: ["property_type"] },
    {
      id: "details",
      title: "Details",
      fieldIds: ["bedrooms", "bathrooms", "toilets", "amenities"],
    },
    {
      id: "location",
      title: "Location",
      fieldIds: ["state", "city", "area", "landmark", "address_hint"],
    },
    {
      id: "pricing",
      title: "Pricing",
      fieldIds: ["title", "price", "payment_period", "description", "video_url"],
    },
    { id: "photos", title: "Photos", fieldIds: [] },
    { id: "review", title: "Review", fieldIds: [] },
  ],
  fields: [
    {
      id: "listing_type",
      label: "Listing type",
      input: "select",
      required: true,
      dependsOn: { watch: [], optionsFrom: "property.listing_types" },
      submitKey: "listing_type",
    },
    {
      id: "property_type",
      label: "Property type",
      input: "select",
      required: true,
      dependsOn: { watch: ["listing_type"], optionsFrom: "property.types_for_listing", clearIfInvalid: true },
      submitKey: "property_type",
    },
    {
      id: "bedrooms",
      label: "Bedrooms",
      input: "number",
      visible: { op: "rule", id: "property.show_room_fields" },
      validation: [{ type: "min", value: 0 }],
      submitKey: "bedrooms",
    },
    {
      id: "bathrooms",
      label: "Bathrooms",
      input: "number",
      visible: { op: "rule", id: "property.show_room_fields" },
      validation: [{ type: "min", value: 0 }],
      submitKey: "bathrooms",
    },
    {
      id: "toilets",
      label: "Toilets",
      input: "number",
      visible: { op: "rule", id: "property.show_room_fields" },
      validation: [{ type: "min", value: 0 }],
      submitKey: "toilets",
    },
    {
      id: "amenities",
      label: "Amenities",
      input: "multiselect",
      defaultValue: [],
      dependsOn: { watch: [], optionsFrom: "property.amenities" },
      submitKey: "amenities",
    },
    {
      id: "state",
      label: "State",
      input: "select",
      required: true,
      dependsOn: { watch: [], optionsFrom: "property.states" },
      submitKey: "state",
    },
    {
      id: "city",
      label: "City",
      input: "select",
      required: true,
      dependsOn: { watch: ["state"], optionsFrom: "property.cities_for_state", clearIfInvalid: true },
      submitKey: "city",
    },
    {
      id: "area",
      label: "Area",
      input: "select",
      dependsOn: { watch: ["city"], optionsFrom: "property.areas_for_city", clearIfInvalid: false },
      submitKey: "area",
    },
    { id: "landmark", label: "Landmark", input: "text", advanced: true, submitKey: "landmark" },
    {
      id: "address_hint",
      label: "Address hint",
      input: "text",
      advanced: true,
      submitKey: "address_hint",
    },
    {
      id: "title",
      label: "Title",
      input: "text",
      required: true,
      validation: [{ type: "minLength", value: 6 }],
      submitKey: "title",
    },
    {
      id: "price",
      label: "Price (₦)",
      input: "currency",
      required: true,
      validation: [{ type: "min", value: 1 }],
      submitKey: "price",
    },
    {
      id: "payment_period",
      label: "Payment period",
      input: "select",
      defaultValue: "yearly",
      options: [
        { value: "yearly", label: "Per year" },
        { value: "monthly", label: "Per month" },
        { value: "weekly", label: "Per week" },
        { value: "daily", label: "Per night" },
        { value: "total", label: "Total price" },
      ],
      submitKey: "payment_period",
    },
    {
      id: "description",
      label: "Description",
      input: "textarea",
      submitKey: "description",
    },
    {
      id: "video_url",
      label: "Video link",
      input: "text",
      advanced: true,
      placeholder: "Video link (optional)",
      submitKey: "video_url",
    },
  ],
  photo: {
    min: 2,
    max: 20,
    tips: ["Exterior", "Living room", "Kitchen", "Bedrooms", "Bathrooms", "Compound"],
    recommendedCover: "first",
  },
  autofill: {
    titleRecipe: ["bedrooms", "property_type", "city"],
    descriptionRecipe: "off",
    photoChecklistFromTips: true,
  },
  review: {
    checklist: ["photos", "price", "location", "details"],
    showLivePreview: true,
    successMessageAfterSubmitOnly: true,
  },
};
