/**
 * Vehicle category manifest — metadata only. No vehicle-specific logic
 * lives outside this file; engines resolve everything from here.
 */
import type { CategoryManifest } from "../types";
import { VEHICLE_PHOTO_RULES } from "../photo-schema/rules";

const CATEGORIES_WITH_VIN_FIELDS = ["car", "suv", "truck", "van", "commercial"];

export const VEHICLE_CATEGORY_MANIFEST: CategoryManifest = {
  id: "vehicle",
  version: 1,
  label: "Vehicle",
  assetType: "VEHICLE",
  submitAdapter: "vehicle",
  capabilities: ["vin_lookup_reserved"],
  steps: [
    { id: "type", title: "Category", fieldIds: ["auto_category"] },
    { id: "identity", title: "Identity", fieldIds: ["make", "model", "year", "vehicle_condition"] },
    {
      id: "specs",
      title: "Specs",
      fieldIds: [
        "trim",
        "transmission",
        "fuel_type",
        "mileage",
        "vin",
        "exterior_color",
        "interior_color",
        "body_type",
        "drivetrain",
        "engine",
        "registration_status",
        "financing_available",
      ],
    },
    { id: "location", title: "Location", fieldIds: ["state", "city", "area"] },
    { id: "pricing", title: "Pricing", fieldIds: ["title", "price", "description"] },
    { id: "photos", title: "Photos", fieldIds: [] },
    { id: "review", title: "Review", fieldIds: [] },
  ],
  fields: [
    {
      id: "auto_category",
      label: "Vehicle type",
      input: "select",
      required: true,
      dependsOn: { watch: [], optionsFrom: "vehicle.types" },
      submitKey: "auto_category",
    },
    {
      id: "make",
      label: "Make",
      input: "select",
      required: true,
      dependsOn: { watch: [], optionsFrom: "vehicle.makes" },
      submitKey: "make",
    },
    {
      id: "model",
      label: "Model",
      input: "select",
      required: true,
      dependsOn: { watch: ["make"], optionsFrom: "vehicle.models_for_make", clearIfInvalid: true },
      submitKey: "model",
    },
    {
      id: "year",
      label: "Year",
      input: "year",
      required: true,
      validation: [{ type: "min", value: 1980 }, { type: "integer" }],
      submitKey: "year",
    },
    {
      id: "vehicle_condition",
      label: "Condition",
      input: "select",
      required: true,
      dependsOn: { watch: [], optionsFrom: "vehicle.condition" },
      submitKey: "vehicle_condition",
    },
    { id: "trim", label: "Trim", input: "text", placeholder: "XLE", submitKey: "trim" },
    {
      id: "transmission",
      label: "Transmission",
      input: "select",
      dependsOn: { watch: [], optionsFrom: "vehicle.transmission" },
      submitKey: "transmission",
    },
    {
      id: "fuel_type",
      label: "Fuel type",
      input: "select",
      dependsOn: { watch: [], optionsFrom: "vehicle.fuel_type" },
      submitKey: "fuel_type",
    },
    {
      id: "mileage",
      label: "Mileage (km)",
      input: "number",
      validation: [{ type: "min", value: 0 }],
      submitKey: "mileage",
    },
    {
      id: "vin",
      label: "VIN",
      input: "text",
      placeholder: "Optional",
      advanced: true,
      visible: { op: "equals", field: "auto_category", value: CATEGORIES_WITH_VIN_FIELDS },
      submitKey: "vin",
    },
    { id: "exterior_color", label: "Exterior color", input: "text", submitKey: "exterior_color" },
    {
      id: "interior_color",
      label: "Interior color",
      input: "text",
      advanced: true,
      visible: { op: "equals", field: "auto_category", value: CATEGORIES_WITH_VIN_FIELDS },
      submitKey: "interior_color",
    },
    {
      id: "body_type",
      label: "Body type",
      input: "select",
      visible: { op: "equals", field: "auto_category", value: CATEGORIES_WITH_VIN_FIELDS },
      dependsOn: { watch: [], optionsFrom: "vehicle.body_type" },
      submitKey: "body_type",
    },
    {
      id: "drivetrain",
      label: "Drivetrain",
      input: "select",
      advanced: true,
      visible: { op: "equals", field: "auto_category", value: CATEGORIES_WITH_VIN_FIELDS },
      dependsOn: { watch: [], optionsFrom: "vehicle.drivetrain" },
      submitKey: "drivetrain",
    },
    { id: "engine", label: "Engine", input: "text", placeholder: "2.5L I4", submitKey: "engine" },
    {
      id: "registration_status",
      label: "Registration status",
      input: "select",
      dependsOn: { watch: [], optionsFrom: "vehicle.registration_status" },
      submitKey: "registration_status",
    },
    {
      id: "financing_available",
      label: "Financing available",
      input: "boolean",
      advanced: true,
      submitKey: "financing_available",
    },
    {
      id: "state",
      label: "State",
      input: "select",
      required: true,
      dependsOn: { watch: [], optionsFrom: "property.states" },
      submitKey: "state",
    },
    {
      id: "city",
      label: "City",
      input: "select",
      required: true,
      dependsOn: { watch: ["state"], optionsFrom: "property.cities_for_state", clearIfInvalid: true },
      submitKey: "city",
    },
    {
      id: "area",
      label: "Area",
      input: "select",
      dependsOn: { watch: ["city"], optionsFrom: "property.areas_for_city", clearIfInvalid: false },
      submitKey: "area",
    },
    {
      id: "title",
      label: "Title",
      input: "text",
      required: true,
      placeholder: "Auto-suggested from make, model, year",
      autofill: { confirmOnly: false },
      submitKey: "title",
    },
    {
      id: "price",
      label: "Price (₦)",
      input: "currency",
      required: true,
      validation: [{ type: "min", value: 1 }],
      submitKey: "price",
    },
    {
      id: "description",
      label: "Description",
      input: "textarea",
      placeholder: "Optional — highlight condition and history",
      submitKey: "description",
    },
  ],
  photo: VEHICLE_PHOTO_RULES,
  autofill: {
    titleRecipe: ["year", "make", "model", "transmission"],
    descriptionRecipe: "off",
    photoChecklistFromTips: true,
  },
  review: {
    checklist: ["photos", "price", "location", "details"],
    showLivePreview: true,
    successMessageAfterSubmitOnly: true,
  },
};
